const Ciudades = () => {
  return (
    <>
  <option value="" disabled selected>¿A donde quieres viajar?</option>
  <option value="Abejorral (Antioquia)">Abejorral (Antioquia)</option>
  <option value="Abrego (Norte de Santander)">Abrego (Norte de Santander)</option>
  <option value="Abriaquí (Antioquia)">Abriaquí (Antioquia)</option>
  <option value="Acacías (Meta)">Acacías (Meta)</option>
  <option value="Acandí (Chocó)">Acandí (Chocó)</option>
  <option value="Acevedo (Huila)">Acevedo (Huila)</option>
  <option value="Achí (Bolívar)">Achí (Bolívar)</option>
  <option value="Agrado (Huila)">Agrado (Huila)</option>
  <option value="Agua de Dios (Cundinamarca)">Agua de Dios (Cundinamarca)</option>
  <option value="Aguachica (Cesar)">Aguachica (Cesar)</option>
  <option value="Aguada (Santander)">Aguada (Santander)</option>
  <option value="Aguadas (Caldas)">Aguadas (Caldas)</option>
  <option value="Aguazul (Casanare)">Aguazul (Casanare)</option>
  <option value="Agustín Codazzi (Cesar)">Agustín Codazzi (Cesar)</option>
  <option value="Aipe (Huila)">Aipe (Huila)</option>
  <option value="Albán (Cundinamarca)">Albán (Cundinamarca)</option>
  <option value="Albán (Nariño)">Albán (Nariño)</option>
  <option value="Albania (Caquetá)">Albania (Caquetá)</option>
  <option value="Albania (La Guajira)">Albania (La Guajira)</option>
  <option value="Albania (Santander)">Albania (Santander)</option>
  <option value="Alcalá (Valle del Cauca)">Alcalá (Valle del Cauca)</option>
  <option value="Aldana (Nariño)">Aldana (Nariño)</option>
  <option value="Alejandría (Antioquia)">Alejandría (Antioquia)</option>
  <option value="Algarrobo (Magdalena)">Algarrobo (Magdalena)</option>
  <option value="Algeciras (Huila)">Algeciras (Huila)</option>
  <option value="Almaguer (Cauca)">Almaguer (Cauca)</option>
  <option value="Almeida (Boyacá)">Almeida (Boyacá)</option>
  <option value="Alpujarra (Tolima)">Alpujarra (Tolima)</option>
  <option value="Altamira (Huila)">Altamira (Huila)</option>
  <option value="Alto Baudo (Chocó)">Alto Baudo (Chocó)</option>
  <option value="Altos del Rosario (Bolívar)">Altos del Rosario (Bolívar)</option>
  <option value="Alvarado (Tolima)">Alvarado (Tolima)</option>
  <option value="Amagá (Antioquia)">Amagá (Antioquia)</option>
  <option value="Amalfi (Antioquia)">Amalfi (Antioquia)</option>
  <option value="Ambalema (Tolima)">Ambalema (Tolima)</option>
  <option value="Anapoima (Cundinamarca)">Anapoima (Cundinamarca)</option>
  <option value="Ancuyá (Nariño)">Ancuyá (Nariño)</option>
  <option value="Andalucía (Valle del Cauca)">Andalucía (Valle del Cauca)</option>
  <option value="Andes (Antioquia)">Andes (Antioquia)</option>
  <option value="Angelópolis (Antioquia)">Angelópolis (Antioquia)</option>
  <option value="Angostura (Antioquia)">Angostura (Antioquia)</option>
  <option value="Anolaima (Cundinamarca)">Anolaima (Cundinamarca)</option>
  <option value="Anorí (Antioquia)">Anorí (Antioquia)</option>
  <option value="Anserma (Caldas)">Anserma (Caldas)</option>
  <option value="Ansermanuevo (Valle del Cauca)">Ansermanuevo (Valle del Cauca)</option>
  <option value="Anza (Antioquia)">Anza (Antioquia)</option>
  <option value="Anzoátegui (Tolima)">Anzoátegui (Tolima)</option>
  <option value="Apartadó (Antioquia)">Apartadó (Antioquia)</option>
  <option value="Apía (Risaralda)">Apía (Risaralda)</option>
  <option value="Apulo (Cundinamarca)">Apulo (Cundinamarca)</option>
  <option value="Aquitania (Boyacá)">Aquitania (Boyacá)</option>
  <option value="Aracataca (Magdalena)">Aracataca (Magdalena)</option>
  <option value="Aranzazu (Caldas)">Aranzazu (Caldas)</option>
  <option value="Aratoca (Santander)">Aratoca (Santander)</option>
  <option value="Arauca (Arauca)">Arauca (Arauca)</option>
  <option value="Arauquita (Arauca)">Arauquita (Arauca)</option>
  <option value="Arbeláez (Cundinamarca)">Arbeláez (Cundinamarca)</option>
  <option value="Arboleda (Nariño)">Arboleda (Nariño)</option>
  <option value="Arboledas (Norte de Santander)">Arboledas (Norte de Santander)</option>
  <option value="Arboletes (Antioquia)">Arboletes (Antioquia)</option>
  <option value="Arcabuco (Boyacá)">Arcabuco (Boyacá)</option>
  <option value="Arenal (Bolívar)">Arenal (Bolívar)</option>
  <option value="Argelia (Antioquia)">Argelia (Antioquia)</option>
  <option value="Argelia (Cauca)">Argelia (Cauca)</option>
  <option value="Argelia (Valle del Cauca)">Argelia (Valle del Cauca)</option>
  <option value="Ariguaní (Magdalena)">Ariguaní (Magdalena)</option>
  <option value="Arjona (Bolívar)">Arjona (Bolívar)</option>
  <option value="Armenia (Antioquia)">Armenia (Antioquia)</option>
  <option value="Armenia (Quindío)">Armenia (Quindío)</option>
  <option value="Armero (Tolima)">Armero (Tolima)</option>
  <option value="Arroyohondo (Bolívar)">Arroyohondo (Bolívar)</option>
<option value="Astrea (Cesar)">Astrea (Cesar)</option>
<option value="Ataco (Tolima)">Ataco (Tolima)</option>
<option value="Atrato (Chocó)">Atrato (Chocó)</option>
<option value="Ayapel (Córdoba)">Ayapel (Córdoba)</option>
<option value="Bagadó (Chocó)">Bagadó (Chocó)</option>
<option value="Bahía Solano (Chocó)">Bahía Solano (Chocó)</option>
<option value="Bajo Baudó (Chocó)">Bajo Baudó (Chocó)</option>
<option value="Balboa (Cauca)">Balboa (Cauca)</option>
<option value="Balboa (Risaralda)">Balboa (Risaralda)</option>
<option value="Baranoa (Atlántico)">Baranoa (Atlántico)</option>
<option value="Baraya (Huila)">Baraya (Huila)</option>
<option value="Barbacoas (Nariño)">Barbacoas (Nariño)</option>
<option value="Barbosa (Antioquia)">Barbosa (Antioquia)</option>
<option value="Barbosa (Santander)">Barbosa (Santander)</option>
<option value="Barichara (Santander)">Barichara (Santander)</option>
<option value="Barranca de Upía (Meta)">Barranca de Upía (Meta)</option>
<option value="Barrancabermeja (Santander)">Barrancabermeja (Santander)</option>
<option value="Barrancas (La Guajira)">Barrancas (La Guajira)</option>
<option value="Barranco de Loba (Bolívar)">Barranco de Loba (Bolívar)</option>
<option value="Barranco Minas (Guainía)">Barranco Minas (Guainía)</option>
<option value="Barranquilla (Atlántico)">Barranquilla (Atlántico)</option>
<option value="Becerril (Cesar)">Becerril (Cesar)</option>
<option value="Belalcázar (Caldas)">Belalcázar (Caldas)</option>
<option value="Belén (Boyacá)">Belén (Boyacá)</option>
<option value="Belén (Nariño)">Belén (Nariño)</option>
<option value="Belén de Bajirá (Chocó)">Belén de Bajirá (Chocó)</option>
<option value="Belén de Los Andaquies (Caquetá)">Belén de Los Andaquies (Caquetá)</option>
<option value="Belén de Umbría (Risaralda)">Belén de Umbría (Risaralda)</option>
<option value="Bello (Antioquia)">Bello (Antioquia)</option>
<option value="Belmira (Antioquia)">Belmira (Antioquia)</option>
<option value="Beltrán (Cundinamarca)">Beltrán (Cundinamarca)</option>
<option value="Berbeo (Boyacá)">Berbeo (Boyacá)</option>
<option value="Betania (Antioquia)">Betania (Antioquia)</option>
<option value="Betéitiva (Boyacá)">Betéitiva (Boyacá)</option>
<option value="Betulia (Antioquia)">Betulia (Antioquia)</option>
<option value="Betulia (Santander)">Betulia (Santander)</option>
<option value="Bituima (Cundinamarca)">Bituima (Cundinamarca)</option>
<option value="Boavita (Boyacá)">Boavita (Boyacá)</option>
<option value="Bochalema (Norte de Santander)">Bochalema (Norte de Santander)</option>
<option value="Bogotá (Cundinamarca)">Bogotá (Cundinamarca)</option>
<option value="Bojacá (Cundinamarca)">Bojacá (Cundinamarca)</option>
<option value="Bojaya (Chocó)">Bojaya (Chocó)</option>
<option value="Bolívar (Antioquia)">Bolívar (Antioquia)</option>
<option value="Bolívar (Cauca)">Bolívar (Cauca)</option>
<option value="Bolívar (Valle del Cauca)">Bolívar (Valle del Cauca)</option>
<option value="Bosconia (Cesar)">Bosconia (Cesar)</option>
<option value="Boyacá (Boyacá)">Boyacá (Boyacá)</option>
<option value="Briceño (Antioquia)">Briceño (Antioquia)</option>
<option value="Briceño (Boyacá)">Briceño (Boyacá)</option>
<option value="Bucaramanga (Santander)">Bucaramanga (Santander)</option>
<option value="Bucarasica (Norte de Santander)">Bucarasica (Norte de Santander)</option>
<option value="Buenaventura (Valle del Cauca)">Buenaventura (Valle del Cauca)</option>
<option value="Buenavista (Boyacá)">Buenavista (Boyacá)</option>
<option value="Buenavista (Córdoba)">Buenavista (Córdoba)</option>
<option value="Buenavista (Quindío)">Buenavista (Quindío)</option>
<option value="Buenavista (Sucre)">Buenavista (Sucre)</option>
<option value="Buenos Aires (Cauca)">Buenos Aires (Cauca)</option>
<option value="Buesaco (Nariño)">Buesaco (Nariño)</option>
<option value="Buga (Valle del Cauca)">Buga (Valle del Cauca)</option>
<option value="Bugalagrande (Valle del Cauca)">Bugalagrande (Valle del Cauca)</option>
<option value="Buriticá (Antioquia)">Buriticá (Antioquia)</option>
<option value="Busbanzá (Boyacá)">Busbanzá (Boyacá)</option>
<option value="Cabrera (Cundinamarca)">Cabrera (Cundinamarca)</option>
<option value="Cabrera (Nariño)">Cabrera (Nariño)</option>
<option value="Cabuyaro (Meta)">Cabuyaro (Meta)</option>
<option value="Cacahual (Norte de Santander)">Cacahual (Norte de Santander)</option>
<option value="Cáceres (Antioquia)">Cáceres (Antioquia)</option>
<option value="Cachipay (Cundinamarca)">Cachipay (Cundinamarca)</option>
<option value="Cachirá (Norte de Santander)">Cachirá (Norte de Santander)</option>
<option value="Cacota (Boyacá)">Cacota (Boyacá)</option>
<option value="Caicedo (Valle del Cauca)">Caicedo (Valle del Cauca)</option>
<option value="Caicedonia (Valle del Cauca)">Caicedonia (Valle del Cauca)</option>
<option value="Caimito (Sucre)">Caimito (Sucre)</option>
<option value="Cajamarca (Tolima)">Cajamarca (Tolima)</option>
<option value="Cajibío (Cauca)">Cajibío (Cauca)</option>
<option value="Cajicá (Cundinamarca)">Cajicá (Cundinamarca)</option>
<option value="Calamar (Bolívar)">Calamar (Bolívar)</option>
<option value="Calamar (Guaviare)">Calamar (Guaviare)</option>
<option value="Calarca (Quindío)">Calarca (Quindío)</option>
<option value="Caldas (Antioquia)">Caldas (Antioquia)</option>
<option value="Caldas (Boyacá)">Caldas (Boyacá)</option>
<option value="Caldono (Cauca)">Caldono (Cauca)</option>
<option value="Cali (Valle del Cauca)">Cali (Valle del Cauca)</option>
<option value="California (Santander)">California (Santander)</option>
<option value="Calima (Valle del Cauca)">Calima (Valle del Cauca)</option>
<option value="Caloto (Cauca)">Caloto (Cauca)</option>
<option value="Campamento (Antioquia)">Campamento (Antioquia)</option>
<option value="Campo de la Cruz (Atlántico)">Campo de la Cruz (Atlántico)</option>
<option value="Campoalegre (Huila)">Campoalegre (Huila)</option>
<option value="Campohermoso (Boyacá)">Campohermoso (Boyacá)</option>
<option value="Canalete (Córdoba)">Canalete (Córdoba)</option>
<option value="Cañasgordas (Antioquia)">Cañasgordas (Antioquia)</option>
<option value="Candelaria (Atlántico)">Candelaria (Atlántico)</option>
<option value="Candelaria (Valle del Cauca)">Candelaria (Valle del Cauca)</option>
<option value="Cantagallo (Bolívar)">Cantagallo (Bolívar)</option>
<option value="Caparrapí (Cundinamarca)">Caparrapí (Cundinamarca)</option>
<option value="Capitanejo (Santander)">Capitanejo (Santander)</option>
<option value="Caqueza (Cundinamarca)">Caqueza (Cundinamarca)</option>
<option value="Caracolí (Antioquia)">Caracolí (Antioquia)</option>
<option value="Caramanta (Antioquia)">Caramanta (Antioquia)</option>
<option value="Carcasí (Santander)">Carcasí (Santander)</option>
<option value="Carepa (Antioquia)">Carepa (Antioquia)</option>
<option value="Carmen de Apicalá (Tolima)">Carmen de Apicalá (Tolima)</option>
<option value="Carmen de Carupa (Cundinamarca)">Carmen de Carupa (Cundinamarca)</option>
<option value="Carmen del Darien (Chocó)">Carmen del Darien (Chocó)</option>
<option value="Carmen del Viboral (Antioquia)">Carmen del Viboral (Antioquia)</option>
<option value="Carolina (Antioquia)">Carolina (Antioquia)</option>
<option value="Cartagena (Bolívar)">Cartagena (Bolívar)</option>
<option value="Cartagena del Chairá (Caquetá)">Cartagena del Chairá (Caquetá)</option>
<option value="Cartago (Valle del Cauca)">Cartago (Valle del Cauca)</option>
<option value="Caruru (Vaupés)">Caruru (Vaupés)</option>
<option value="Casabianca (Tolima)">Casabianca (Tolima)</option>
<option value="Castilla La Nueva (Meta)">Castilla La Nueva (Meta)</option>
<option value="Caucasia (Antioquia)">Caucasia (Antioquia)</option>
<option value="Cepitá (Santander)">Cepitá (Santander)</option>
<option value="Cereté (Córdoba)">Cereté (Córdoba)</option>
<option value="Cerinza (Boyacá)">Cerinza (Boyacá)</option>
<option value="Cerrito (Santander)">Cerrito (Santander)</option>
<option value="Cerro San Antonio (Magdalena)">Cerro San Antonio (Magdalena)</option>
<option value="Cértegui (Chocó)">Cértegui (Chocó)</option>
<option value="Chachagüí (Nariño)">Chachagüí (Nariño)</option>
<option value="Chaguaní (Cundinamarca)">Chaguaní (Cundinamarca)</option>
<option value="Chalán (Sucre)">Chalán (Sucre)</option>
<option value="Chameza (Casanare)">Chameza (Casanare)</option>
<option value="Chaparral (Tolima)">Chaparral (Tolima)</option>
<option value="Charalá (Santander)">Charalá (Santander)</option>
<option value="Charta (Santander)">Charta (Santander)</option>
<option value="Chía (Cundinamarca)">Chía (Cundinamarca)</option>
<option value="Chibolo (Magdalena)">Chibolo (Magdalena)</option>
<option value="Chigorodó (Antioquia)">Chigorodó (Antioquia)</option>
<option value="Chima (Santander)">Chima (Santander)</option>
<option value="Chimá (Córdoba)">Chimá (Córdoba)</option>
<option value="Chimichagua (Cesar)">Chimichagua (Cesar)</option>
<option value="Chinácota (Norte de Santander)">Chinácota (Norte de Santander)</option>
<option value="Chinavita (Boyacá)">Chinavita (Boyacá)</option>
<option value="Chinchiná (Caldas)">Chinchiná (Caldas)</option>
<option value="Chinú (Córdoba)">Chinú (Córdoba)</option>
<option value="Chipaque (Cundinamarca)">Chipaque (Cundinamarca)</option>
<option value="Chipatá (Santander)">Chipatá (Santander)</option>
<option value="Chiquinquirá (Boyacá)">Chiquinquirá (Boyacá)</option>
<option value="Chíquiza (Boyacá)">Chíquiza (Boyacá)</option>
<option value="Chiriguaná (Cesar)">Chiriguaná (Cesar)</option>
<option value="Chiscas (Boyacá)">Chiscas (Boyacá)</option>
<option value="Chita (Boyacá)">Chita (Boyacá)</option>
<option value="Chitagá (Norte de Santander)">Chitagá (Norte de Santander)</option>
<option value="Chitaraque (Santander)">Chitaraque (Santander)</option>
<option value="Chivatá (Boyacá)">Chivatá (Boyacá)</option>
<option value="Chivor (Boyacá)">Chivor (Boyacá)</option>
<option value="Choachí (Cundinamarca)">Choachí (Cundinamarca)</option>
<option value="Chocontá (Cundinamarca)">Chocontá (Cundinamarca)</option>
<option value="Cicuco (Bolívar)">Cicuco (Bolívar)</option>
<option value="Ciénaga (Magdalena)">Ciénaga (Magdalena)</option>
<option value="Ciénaga de Oro (Córdoba)">Ciénaga de Oro (Córdoba)</option>
<option value="Ciénega (Boyacá)">Ciénega (Boyacá)</option>
<option value="Cimitarra (Santander)">Cimitarra (Santander)</option>
<option value="Circasia (Quindío)">Circasia (Quindío)</option>
<option value="Cisneros (Antioquia)">Cisneros (Antioquia)</option>
<option value="Ciudad Bolívar (Antioquia)">Ciudad Bolívar (Antioquia)</option>
<option value="Clemencia (Bolívar)">Clemencia (Bolívar)</option>
<option value="Cocorná (Antioquia)">Cocorná (Antioquia)</option>
<option value="Coello (Tolima)">Coello (Tolima)</option>
<option value="Cogua (Cundinamarca)">Cogua (Cundinamarca)</option>
<option value="Colombia (Huila)">Colombia (Huila)</option>
<option value="Colón (Putumayo)">Colón (Putumayo)</option>
<option value="Colón (Nariño)">Colón (Nariño)</option>
<option value="Coloso (Sucre)">Coloso (Sucre)</option>
<option value="Cómbita (Boyacá)">Cómbita (Boyacá)</option>
<option value="Concepción (Antioquia)">Concepción (Antioquia)</option>
<option value="Concepción (Santander)">Concepción (Santander)</option>
<option value="Concordia (Antioquia)">Concordia (Antioquia)</option>
<option value="Concordia (Magdalena)">Concordia (Magdalena)</option>
<option value="Condoto (Chocó)">Condoto (Chocó)</option>
<option value="Confines (Santander)">Confines (Santander)</option>
<option value="Consacá (Nariño)">Consacá (Nariño)</option>
<option value="Contadero (Nariño)">Contadero (Nariño)</option>
<option value="Contratación (Santander)">Contratación (Santander)</option>
<option value="Convención (Norte de Santander)">Convención (Norte de Santander)</option>
<option value="Copacabana (Antioquia)">Copacabana (Antioquia)</option>
<option value="Coper (Cauca)">Coper (Cauca)</option>
<option value="Córdoba (Bolívar)">Córdoba (Bolívar)</option>
<option value="Córdoba (Nariño)">Córdoba (Nariño)</option>
<option value="Córdoba (Quindío)">Córdoba (Quindío)</option>
<option value="Corinto (Cauca)">Corinto (Cauca)</option>
<option value="Coromoro (Santander)">Coromoro (Santander)</option>
<option value="Corozal (Sucre)">Corozal (Sucre)</option>
<option value="Corrales (Boyacá)">Corrales (Boyacá)</option>
<option value="Cota (Cundinamarca)">Cota (Cundinamarca)</option>
<option value="Cotorra (Córdoba)">Cotorra (Córdoba)</option>
<option value="Covarachía (Boyacá)">Covarachía (Boyacá)</option>
<option value="Coveñas (Sucre)">Coveñas (Sucre)</option>
<option value="Coyaima (Tolima)">Coyaima (Tolima)</option>
<option value="Cravo Norte (Arauca)">Cravo Norte (Arauca)</option>
<option value="Cuaspud (Nariño)">Cuaspud (Nariño)</option>
<option value="Cubará (Boyacá)">Cubará (Boyacá)</option>
<option value="Cubarral (Meta)">Cubarral (Meta)</option>
<option value="Cucaita (Boyacá)">Cucaita (Boyacá)</option>
<option value="Cucunubá (Cundinamarca)">Cucunubá (Cundinamarca)</option>
<option value="Cúcuta (Norte de Santander)">Cúcuta (Norte de Santander)</option>
<option value="Cucutilla (Norte de Santander)">Cucutilla (Norte de Santander)</option>
<option value="Cuítiva (Boyacá)">Cuítiva (Boyacá)</option>
<option value="Cumaral (Meta)">Cumaral (Meta)</option>
<option value="Cumaribo (Vichada)">Cumaribo (Vichada)</option>
<option value="Cumbal (Nariño)">Cumbal (Nariño)</option>
<option value="Cumbitara (Nariño)">Cumbitara (Nariño)</option>
<option value="Cunday (Tolima)">Cunday (Tolima)</option>
<option value="Curillo (Caquetá)">Curillo (Caquetá)</option>
<option value="Curití (Santander)">Curití (Santander)</option>
<option value="Curumaní (Cesar)">Curumaní (Cesar)</option>
<option value="Dabeiba (Antioquia)">Dabeiba (Antioquia)</option>
<option value="Dagua (Valle del Cauca)">Dagua (Valle del Cauca)</option>
<option value="Dibulla (La Guajira)">Dibulla (La Guajira)</option>
<option value="Distracción (La Guajira)">Distracción (La Guajira)</option>
<option value="Dolores (Tolima)">Dolores (Tolima)</option>
<option value="Don Matías (Antioquia)">Don Matías (Antioquia)</option>
<option value="Dosquebradas (Risaralda)">Dosquebradas (Risaralda)</option>
<option value="Duitama (Boyacá)">Duitama (Boyacá)</option>
<option value="Durania (Norte de Santander)">Durania (Norte de Santander)</option>
<option value="Ebéjico (Antioquia)">Ebéjico (Antioquia)</option>
<option value="El Águila (Huila)">El Águila (Huila)</option>
<option value="El Bagre (Antioquia)">El Bagre (Antioquia)</option>
<option value="El Banco (Magdalena)">El Banco (Magdalena)</option>
<option value="El Cairo (Valle del Cauca)">El Cairo (Valle del Cauca)</option>
<option value="El Calvario (Meta)">El Calvario (Meta)</option>
<option value="El Cantón del San Pablo (Nariño)">El Cantón del San Pablo (Nariño)</option>
<option value="El Carmen (Norte de Santander)">El Carmen (Norte de Santander)</option>
<option value="El Carmen de Atrato (Chocó)">El Carmen de Atrato (Chocó)</option>
<option value="El Carmen de Bolívar (Bolívar)">El Carmen de Bolívar (Bolívar)</option>
<option value="El Carmen de Chucurí (Santander)">El Carmen de Chucurí (Santander)</option>
<option value="El Carmen de Viboral (Antioquia)">El Carmen de Viboral (Antioquia)</option>
<option value="El Castillo (Meta)">El Castillo (Meta)</option>
<option value="El Cerrito (Valle del Cauca)">El Cerrito (Valle del Cauca)</option>
<option value="El Charco (Nariño)">El Charco (Nariño)</option>
<option value="El Cocuy (Boyacá)">El Cocuy (Boyacá)</option>
<option value="El Colegio (Cundinamarca)">El Colegio (Cundinamarca)</option>
<option value="El Copey (Cesar)">El Copey (Cesar)</option>
<option value="El Doncello (Caquetá)">El Doncello (Caquetá)</option>
<option value="El Dorado (Meta)">El Dorado (Meta)</option>
<option value="El Dovio (Valle del Cauca)">El Dovio (Valle del Cauca)</option>
<option value="El Encanto (Amazonas)">El Encanto (Amazonas)</option>
<option value="El Espino (Boyacá)">El Espino (Boyacá)</option>
<option value="El Guacamayo (Vichada)">El Guacamayo (Vichada)</option>
<option value="El Guamo (Tolima)">El Guamo (Tolima)</option>
<option value="El Litoral del San Juan (Chocó)">El Litoral del San Juan (Chocó)</option>
<option value="El Molino (La Guajira)">El Molino (La Guajira)</option>
<option value="El Paso (Cesar)">El Paso (Cesar)</option>
<option value="El Paujil (Caquetá)">El Paujil (Caquetá)</option>
<option value="El Peñol (Antioquia)">El Peñol (Antioquia)</option>
<option value="El Peñón (Bolívar)">El Peñón (Bolívar)</option>
<option value="El Peñón (Cundinamarca)">El Peñón (Cundinamarca)</option>
<option value="El Peñón (Norte de Santander)">El Peñón (Norte de Santander)</option>
<option value="El Piñón (Magdalena)">El Piñón (Magdalena)</option>
<option value="El Playón (Santander)">El Playón (Santander)</option>
<option value="El Retén (Magdalena)">El Retén (Magdalena)</option>
<option value="El Retorno (Guaviare)">El Retorno (Guaviare)</option>
<option value="El Roble (Sucre)">El Roble (Sucre)</option>
<option value="El Rosal (Cundinamarca)">El Rosal (Cundinamarca)</option>
<option value="El Rosario (Nariño)">El Rosario (Nariño)</option>
<option value="El Santuario (Antioquia)">El Santuario (Antioquia)</option>
<option value="El Tablón de Gómez (Nariño)">El Tablón de Gómez (Nariño)</option>
<option value="El Tambo (Cauca)">El Tambo (Cauca)</option>
<option value="El Tambo (Nariño)">El Tambo (Nariño)</option>
<option value="El Tarra (Norte de Santander)">El Tarra (Norte de Santander)</option>
<option value="El Zulia (Norte de Santander)">El Zulia (Norte de Santander)</option>
<option value="Elías (Huila)">Elías (Huila)</option>
<option value="Encino (Santander)">Encino (Santander)</option>
<option value="Enciso (Santander)">Enciso (Santander)</option>
<option value="Entrerrios (Antioquia)">Entrerrios (Antioquia)</option>
<option value="Envigado (Antioquia)">Envigado (Antioquia)</option>
<option value="Espinal (Tolima)">Espinal (Tolima)</option>
<option value="Facatativá (Cundinamarca)">Facatativá (Cundinamarca)</option>
<option value="Falan (Tolima)">Falan (Tolima)</option>
<option value="Filadelfia (Caldas)">Filadelfia (Caldas)</option>
<option value="Filandia (Quindío)">Filandia (Quindío)</option>
<option value="Firavitoba (Boyacá)">Firavitoba (Boyacá)</option>
<option value="Flandes (Tolima)">Flandes (Tolima)</option>
<option value="Florencia (Caquetá)">Florencia (Caquetá)</option>
<option value="Florencia (Antioquia)">Florencia (Antioquia)</option>
<option value="Floresta (Boyacá)">Floresta (Boyacá)</option>
<option value="Florián (Santander)">Florián (Santander)</option>
<option value="Florida (Valle del Cauca)">Florida (Valle del Cauca)</option>
<option value="Floridablanca (Santander)">Floridablanca (Santander)</option>
<option value="Fomeque (Cundinamarca)">Fomeque (Cundinamarca)</option>
<option value="Fonseca (La Guajira)">Fonseca (La Guajira)</option>
<option value="Fortul (Arauca)">Fortul (Arauca)</option>
<option value="Fosca (Boyacá)">Fosca (Boyacá)</option>
<option value="Francisco Pizarro (Nariño)">Francisco Pizarro (Nariño)</option>
<option value="Fredonia (Antioquia)">Fredonia (Antioquia)</option>
<option value="Fresno (Tolima)">Fresno (Tolima)</option>
<option value="Frontino (Antioquia)">Frontino (Antioquia)</option>
<option value="Fuente de Oro (Meta)">Fuente de Oro (Meta)</option>
<option value="Fundación (Magdalena)">Fundación (Magdalena)</option>
<option value="Funes (Nariño)">Funes (Nariño)</option>
<option value="Funza (Cundinamarca)">Funza (Cundinamarca)</option>
<option value="Fúquene (Cundinamarca)">Fúquene (Cundinamarca)</option>
<option value="Fusagasugá (Cundinamarca)">Fusagasugá (Cundinamarca)</option>
<option value="Gachala (Cundinamarca)">Gachala (Cundinamarca)</option>
<option value="Gachancipá (Cundinamarca)">Gachancipá (Cundinamarca)</option>
<option value="Gachantivá (Boyacá)">Gachantivá (Boyacá)</option>
<option value="Gachetá (Cundinamarca)">Gachetá (Cundinamarca)</option>
<option value="Galán (Santander)">Galán (Santander)</option>
<option value="Galapa (Atlántico)">Galapa (Atlántico)</option>
<option value="Galeras (Sucre)">Galeras (Sucre)</option>
<option value="Gama (Cundinamarca)">Gama (Cundinamarca)</option>
<option value="Gamarra (Cesar)">Gamarra (Cesar)</option>
<option value="Gambita (Santander)">Gambita (Santander)</option>
<option value="Gameza (Boyacá)">Gameza (Boyacá)</option>
<option value="Garagoa (Boyacá)">Garagoa (Boyacá)</option>
<option value="Garzón (Huila)">Garzón (Huila)</option>
<option value="Génova (Quindío)">Génova (Quindío)</option>
<option value="Gigante (Huila)">Gigante (Huila)</option>
<option value="Ginebra (Valle del Cauca)">Ginebra (Valle del Cauca)</option>
<option value="Giraldo (Antioquia)">Giraldo (Antioquia)</option>
<option value="Girardot (Cundinamarca)">Girardot (Cundinamarca)</option>
<option value="Girardota (Antioquia)">Girardota (Antioquia)</option>
<option value="Girón (Santander)">Girón (Santander)</option>
<option value="Gómez Plata (Antioquia)">Gómez Plata (Antioquia)</option>
<option value="González (Tolima)">González (Tolima)</option>
<option value="Gramalote (Norte de Santander)">Gramalote (Norte de Santander)</option>
<option value="Granada (Meta)">Granada (Meta)</option>
<option value="Granada (Antioquia)">Granada (Antioquia)</option>
<option value="Granada (Cundinamarca)">Granada (Cundinamarca)</option>
<option value="Guaca (Santander)">Guaca (Santander)</option>
<option value="Guacamayas (Boyacá)">Guacamayas (Boyacá)</option>
<option value="Guacarí (Valle del Cauca)">Guacarí (Valle del Cauca)</option>
<option value="Guachetá (Cundinamarca)">Guachetá (Cundinamarca)</option>
<option value="Guachucal (Nariño)">Guachucal (Nariño)</option>
<option value="Guadalupe (Santander)">Guadalupe (Santander)</option>
<option value="Guadalupe (Huila)">Guadalupe (Huila)</option>
<option value="Guadalupe (Antioquia)">Guadalupe (Antioquia)</option>
<option value="Guaduas (Cundinamarca)">Guaduas (Cundinamarca)</option>
<option value="Guaitarilla (Nariño)">Guaitarilla (Nariño)</option>
<option value="Gualmatán (Nariño)">Gualmatán (Nariño)</option>
<option value="Guamal (Magdalena)">Guamal (Magdalena)</option>
<option value="Guamal (Meta)">Guamal (Meta)</option>
<option value="Guamo (Tolima)">Guamo (Tolima)</option>
<option value="Guapi (Cauca)">Guapi (Cauca)</option>
<option value="Guapotá (Santander)">Guapotá (Santander)</option>
<option value="Guaranda (Sucre)">Guaranda (Sucre)</option>
<option value="Guarne (Antioquia)">Guarne (Antioquia)</option>
<option value="Guasca (Cundinamarca)">Guasca (Cundinamarca)</option>
<option value="Guatape (Antioquia)">Guatape (Antioquia)</option>
<option value="Guataquí (Cundinamarca)">Guataquí (Cundinamarca)</option>
<option value="Guatavita (Cundinamarca)">Guatavita (Cundinamarca)</option>
<option value="Guateque (Boyacá)">Guateque (Boyacá)</option>
<option value="Guática (Risaralda)">Guática (Risaralda)</option>
<option value="Guavatá (Santander)">Guavatá (Santander)</option>
<option value="Guayabal de Siquima (Cundinamarca)">Guayabal de Siquima (Cundinamarca)</option>
<option value="Guayabetal (Cundinamarca)">Guayabetal (Cundinamarca)</option>
<option value="Guayatá (Boyacá)">Guayatá (Boyacá)</option>
<option value="Güepsa (Santander)">Güepsa (Santander)</option>
<option value="Güicán (Boyacá)">Güicán (Boyacá)</option>
<option value="Gutiérrez (Cundinamarca)">Gutiérrez (Cundinamarca)</option>
<option value="Hacarí (Norte de Santander)">Hacarí (Norte de Santander)</option>
<option value="Hatillo de Loba (Bolívar)">Hatillo de Loba (Bolívar)</option>
<option value="Hato (Santander)">Hato (Santander)</option>
<option value="Hato Corozal (Casanare)">Hato Corozal (Casanare)</option>
<option value="Hatonuevo (La Guajira)">Hatonuevo (La Guajira)</option>
<option value="Heliconia (Antioquia)">Heliconia (Antioquia)</option>
<option value="Herrán (Norte de Santander)">Herrán (Norte de Santander)</option>
<option value="Herveo (Tolima)">Herveo (Tolima)</option>
<option value="Hispania (Antioquia)">Hispania (Antioquia)</option>
<option value="Hobo (Huila)">Hobo (Huila)</option>
<option value="Honda (Tolima)">Honda (Tolima)</option>
<option value="Ibagué (Tolima)">Ibagué (Tolima)</option>
<option value="Icononzo (Tolima)">Icononzo (Tolima)</option>
<option value="Iles (Nariño)">Iles (Nariño)</option>
<option value="Imués (Nariño)">Imués (Nariño)</option>
<option value="Inírida (Guainía)">Inírida (Guainía)</option>
<option value="Inzá (Cauca)">Inzá (Cauca)</option>
<option value="Ipiales (Nariño)">Ipiales (Nariño)</option>
<option value="Iquira (Huila)">Iquira (Huila)</option>
<option value="Isnos (Huila)">Isnos (Huila)</option>
<option value="Istmina (Chocó)">Istmina (Chocó)</option>
<option value="Itagui (Antioquia)">Itagui (Antioquia)</option>
<option value="Ituango (Antioquia)">Ituango (Antioquia)</option>
<option value="Iza (Boyacá)">Iza (Boyacá)</option>
<option value="Jambaló (Cauca)">Jambaló (Cauca)</option>
<option value="Jamundí (Valle del Cauca)">Jamundí (Valle del Cauca)</option>
<option value="Jardín (Antioquia)">Jardín (Antioquia)</option>
<option value="Jenesano (Boyacá)">Jenesano (Boyacá)</option>
<option value="Jericó (Antioquia)">Jericó (Antioquia)</option>
<option value="Jericó (Boyacá)">Jericó (Boyacá)</option>
<option value="Jerusalén (Cundinamarca)">Jerusalén (Cundinamarca)</option>
<option value="Jesús María (Santander)">Jesús María (Santander)</option>
<option value="Jordán (Santander)">Jordán (Santander)</option>
<option value="Juan de Acosta (Atlántico)">Juan de Acosta (Atlántico)</option>
<option value="Junín (Cundinamarca)">Junín (Cundinamarca)</option>
<option value="Juradó (Chocó)">Juradó (Chocó)</option>
<option value="La Apartada (Córdoba)">La Apartada (Córdoba)</option>
<option value="La Argentina (Huila)">La Argentina (Huila)</option>
<option value="La Belleza (Santander)">La Belleza (Santander)</option>
<option value="La Calera (Cundinamarca)">La Calera (Cundinamarca)</option>
<option value="La Capilla (Norte de Santander)">La Capilla (Norte de Santander)</option>
<option value="La Ceja (Antioquia)">La Ceja (Antioquia)</option>
<option value="La Celia (Valle del Cauca)">La Celia (Valle del Cauca)</option>
<option value="La chorrera (Amazonas)">La chorrera (Amazonas)</option>
<option value="La Cruz (Nariño)">La Cruz (Nariño)</option>
<option value="La Cumbre (Valle del Cauca)">La Cumbre (Valle del Cauca)</option>
<option value="La Dorada (Caldas)">La Dorada (Caldas)</option>
<option value="La Esperanza (Norte de Santander)">La Esperanza (Norte de Santander)</option>
<option value="La Estrella (Antioquia)">La Estrella (Antioquia)</option>
<option value="La Florida (Nariño)">La Florida (Nariño)</option>
<option value="La Gloria (Cesar)">La Gloria (Cesar)</option>
<option value="La Guadalupe (Cesar)">La Guadalupe (Cesar)</option>
<option value="La Jagua de Ibirico (Cesar)">La Jagua de Ibirico (Cesar)</option>
<option value="La Jagua del Pilar (Guajira)">La Jagua del Pilar (Guajira)</option>
<option value="La Llanada (Nariño)">La Llanada (Nariño)</option>
<option value="La Macarena (Meta)">La Macarena (Meta)</option>
<option value="La Merced (Caldas)">La Merced (Caldas)</option>
<option value="La Mesa (Cundinamarca)">La Mesa (Cundinamarca)</option>
<option value="La Montañita (Caquetá)">La Montañita (Caquetá)</option>
<option value="La Palma (Cundinamarca)">La Palma (Cundinamarca)</option>
<option value="La Paz (Cesar)">La Paz (Cesar)</option>
<option value="La Paz (Santander)">La Paz (Santander)</option>
<option value="La pedrera (Amazonas)">La pedrera (Amazonas)</option>
<option value="La Peña (Cundinamarca)">La Peña (Cundinamarca)</option>
<option value="La Pintada (Antioquia)">La Pintada (Antioquia)</option>
<option value="La Plata (Huila)">La Plata (Huila)</option>
<option value="La Playa (Norte de Santander)">La Playa (Norte de Santander)</option>
<option value="La Primavera (Vichada)">La Primavera (Vichada)</option>
<option value="La Salina (Casanare)">La Salina (Casanare)</option>
<option value="La Sierra (Cesar)">La Sierra (Cesar)</option>
<option value="La Tebaida (Quindío)">La Tebaida (Quindío)</option>
<option value="La Tola (Nariño)">La Tola (Nariño)</option>
<option value="La Unión (Antioquia)">La Unión (Antioquia)</option>
<option value="La Unión (Nariño)">La Unión (Nariño)</option>
<option value="La Unión (Sucre)">La Unión (Sucre)</option>
<option value="La Unión (Valle del Cauca)">La Unión (Valle del Cauca)</option>
<option value="La Uvita (Boyacá)">La Uvita (Boyacá)</option>
<option value="La Vega (Cauca)">La Vega (Cauca)</option>
<option value="La Vega (Cundinamarca)">La Vega (Cundinamarca)</option>
<option value="La Victoria (Caldas)">La Victoria (Caldas)</option>
<option value="La Victoria (Valle del Cauca)">La Victoria (Valle del Cauca)</option>
<option value="La victoria (Boyacá)">La victoria (Boyacá)</option>
<option value="La Virginia (Risaralda)">La Virginia (Risaralda)</option>
<option value="Labateca (Norte de Santander)">Labateca (Norte de Santander)</option>
<option value="Labranzagrande (Boyacá)">Labranzagrande (Boyacá)</option>
<option value="Landázuri (Santander)">Landázuri (Santander)</option>
<option value="Lebríja (Santander)">Lebríja (Santander)</option>
<option value="Leguízamo (Putumayo)">Leguízamo (Putumayo)</option>
<option value="Leiva (Nariño)">Leiva (Nariño)</option>
<option value="Lejanías (Meta)">Lejanías (Meta)</option>
<option value="Lenguazaque (Cundinamarca)">Lenguazaque (Cundinamarca)</option>
<option value="Lérida (Tolima)">Lérida (Tolima)</option>
<option value="Leticia (Amazonas)">Leticia (Amazonas)</option>
<option value="Líbano (Tolima)">Líbano (Tolima)</option>
<option value="Liborina (Antioquia)">Liborina (Antioquia)</option>
<option value="Linares (Nariño)">Linares (Nariño)</option>
<option value="Lloró (Chocó)">Lloró (Chocó)</option>
<option value="López (Cauca)">López (Cauca)</option>
<option value="Lorica (Córdoba)">Lorica (Córdoba)</option>
<option value="Los Andes (Nariño)">Los Andes (Nariño)</option>
<option value="Los Córdobas (Bolívar)">Los Córdobas (Bolívar)</option>
<option value="Los Palmitos (Sucre)">Los Palmitos (Sucre)</option>
<option value="Los Patios (Norte de Santander)">Los Patios (Norte de Santander)</option>
<option value="Los Santos (Santander)">Los Santos (Santander)</option>
<option value="Lourdes (Norte de Santander)">Lourdes (Norte de Santander)</option>
<option value="Luruaco (Atlántico)">Luruaco (Atlántico)</option>
<option value="Macanal (Boyacá)">Macanal (Boyacá)</option>
<option value="Macaravita (Santander)">Macaravita (Santander)</option>
<option value="Maceo (Antioquia)">Maceo (Antioquia)</option>
<option value="Macheta (Cundinamarca)">Macheta (Cundinamarca)</option>
<option value="Madrid (Cundinamarca)">Madrid (Cundinamarca)</option>
<option value="Magangué (Bolívar)">Magangué (Bolívar)</option>
<option value="Magüi (Cauca)">Magüi (Cauca)</option>
<option value="Mahates (Bolívar)">Mahates (Bolívar)</option>
<option value="Maicao (Guajira)">Maicao (Guajira)</option>
<option value="Majagual (Sucre)">Majagual (Sucre)</option>
<option value="Málaga (Santander)">Málaga (Santander)</option>
<option value="Malambo (Atlántico)">Malambo (Atlántico)</option>
<option value="Mallama (Nariño)">Mallama (Nariño)</option>
<option value="Manatí (Atlántico)">Manatí (Atlántico)</option>
<option value="Manaure (Cesar)">Manaure (Cesar)</option>
<option value="Manaure (Guajira)">Manaure (Guajira)</option>
<option value="Maní (Casanare)">Maní (Casanare)</option>
<option value="Manizales (Caldas)">Manizales (Caldas)</option>
<option value="Manta (Cundinamarca)">Manta (Cundinamarca)</option>
<option value="Manzanares (Caldas)">Manzanares (Caldas)</option>
<option value="Mapiripán (Meta)">Mapiripán (Meta)</option>
<option value="Mapiripana (Guaviare)">Mapiripana (Guaviare)</option>
<option value="Margarita (Bolívar)">Margarita (Bolívar)</option>
<option value="María La Baja (Bolívar)">María La Baja (Bolívar)</option>
<option value="Marinilla (Antioquia)">Marinilla (Antioquia)</option>
<option value="Maripí (Boyacá)">Maripí (Boyacá)</option>
<option value="Mariquita (Tolima)">Mariquita (Tolima)</option>
<option value="Marmato (Caldas)">Marmato (Caldas)</option>
<option value="Marquetalia (Caldas)">Marquetalia (Caldas)</option>
<option value="Marsella (Risaralda)">Marsella (Risaralda)</option>
<option value="Marulanda (Caldas)">Marulanda (Caldas)</option>
<option value="Matanza (Cundinamarca)">Matanza (Cundinamarca)</option>
<option value="Medellín (Antioquia)">Medellín (Antioquia)</option>
<option value="Medina (Cundinamarca)">Medina (Cundinamarca)</option>
<option value="Medio Atrato (Chocó)">Medio Atrato (Chocó)</option>
<option value="Medio Baudó (Chocó)">Medio Baudó (Chocó)</option>
<option value="Medio San Juan (Chocó)">Medio San Juan (Chocó)</option>
<option value="Melgar (Tolima)">Melgar (Tolima)</option>
<option value="Mercaderes (Cauca)">Mercaderes (Cauca)</option>
<option value="Mesetas (Meta)">Mesetas (Meta)</option>
<option value="Milán (Caquetá)">Milán (Caquetá)</option>
<option value="Miraflores (Boyacá)">Miraflores (Boyacá)</option>
<option value="Miraflores (Guaviare)">Miraflores (Guaviare)</option>
<option value="Miranda (Cauca)">Miranda (Cauca)</option>
<option value="Miriti Paraná (Amazonas)">Miriti Paraná (Amazonas)</option>
<option value="Mistrató (Risaralda)">Mistrató (Risaralda)</option>
<option value="Mitú (Vaupés)">Mitú (Vaupés)</option>
<option value="Mocoa (Putumayo)">Mocoa (Putumayo)</option>
<option value="Mogotes (Santander)">Mogotes (Santander)</option>
<option value="Molagavita (Santander)">Molagavita (Santander)</option>
<option value="Momil (Córdoba)">Momil (Córdoba)</option>
<option value="Mompós (Bolívar)">Mompós (Bolívar)</option>
<option value="Mongua (Boyacá)">Mongua (Boyacá)</option>
<option value="Monguí (Boyacá)">Monguí (Boyacá)</option>
<option value="Moniquirá (Boyacá)">Moniquirá (Boyacá)</option>
    <option value="Moñitos (Córdoba)">Moñitos (Córdoba)</option>
    <option value="Montebello (Antioquia)">Montebello (Antioquia)</option>
    <option value="Montecristo (Bolívar)">Montecristo (Bolívar)</option>
    <option value="Montelíbano (Córdoba)">Montelíbano (Córdoba)</option>
    <option value="Montenegro (Quindío)">Montenegro (Quindío)</option>
    <option value="Montería (Córdoba)">Montería (Córdoba)</option>
    <option value="Monterrey (Casanare)">Monterrey (Casanare)</option>
    <option value="Morales (Bolívar)">Morales (Bolívar)</option>
    <option value="Morales (Cauca)">Morales (Cauca)</option>
    <option value="Morelia (Caquetá)">Morelia (Caquetá)</option>
    <option value="Morichal (Vichada)">Morichal (Vichada)</option>
    <option value="Morroa (Sucre)">Morroa (Sucre)</option>
    <option value="Mosquera (Cundinamarca)">Mosquera (Cundinamarca)</option>
    <option value="Mosquera (Nariño)">Mosquera (Nariño)</option>
    <option value="Motavita (Boyacá)">Motavita (Boyacá)</option>
    <option value="Murillo (Tolima)">Murillo (Tolima)</option>
    <option value="Murindó (Antioquia)">Murindó (Antioquia)</option>
    <option value="Mutatá (Antioquia)">Mutatá (Antioquia)</option>
    <option value="Mutiscua (Norte de Santander)">Mutiscua (Norte de Santander)</option>
    <option value="Muzo (Boyacá)">Muzo (Boyacá)</option>
    <option value="Nariño (Antioquia)">Nariño (Antioquia)</option>
    <option value="Nariño (Nariño)">Nariño (Nariño)</option>
    <option value="Nariño (Valle del Cauca)">Nariño (Valle del Cauca)</option>
    <option value="Nátaga (Huila)">Nátaga (Huila)</option>
    <option value="Natagaima (Tolima)">Natagaima (Tolima)</option>
    <option value="Nechí (Antioquia)">Nechí (Antioquia)</option>
    <option value="Necoclí (Antioquia)">Necoclí (Antioquia)</option>
    <option value="Neira (Caldas)">Neira (Caldas)</option>
    <option value="Neiva (Huila)">Neiva (Huila)</option>
    <option value="Nemocón (Cundinamarca)">Nemocón (Cundinamarca)</option>
    <option value="Nilo (Cundinamarca)">Nilo (Cundinamarca)</option>
    <option value="Nimaima (Cundinamarca)">Nimaima (Cundinamarca)</option>
    <option value="Nobsa (Boyacá)">Nobsa (Boyacá)</option>
    <option value="Nocaima (Cundinamarca)">Nocaima (Cundinamarca)</option>
    <option value="Norcasia (Caldas)">Norcasia (Caldas)</option>
    <option value="Nóvita (Chocó)">Nóvita (Chocó)</option>
    <option value="Nueva Granada (Cundinamarca)">Nueva Granada (Cundinamarca)</option>
    <option value="Nuevo Colón (Boyacá)">Nuevo Colón (Boyacá)</option>
    <option value="Nunchía (Casanare)">Nunchía (Casanare)</option>
    <option value="Nuquí (Chocó)">Nuquí (Chocó)</option>
    <option value="Obando (Valle del Cauca)">Obando (Valle del Cauca)</option>
    <option value="Ocamonte (Santander)">Ocamonte (Santander)</option>
    <option value="Ocaña (Norte de Santander)">Ocaña (Norte de Santander)</option>
    <option value="Oiba (Santander)">Oiba (Santander)</option>
    <option value="Oicatá (Boyacá)">Oicatá (Boyacá)</option>
    <option value="Olaya (Antioquia)">Olaya (Antioquia)</option>
    <option value="Olaya Herrera (Nariño)">Olaya Herrera (Nariño)</option>
    <option value="Onzaga (Santander)">Onzaga (Santander)</option>
    <option value="Oporapa (Huila)">Oporapa (Huila)</option>
    <option value="Orito (Putumayo)">Orito (Putumayo)</option>
    <option value="Orocué (Casanare)">Orocué (Casanare)</option>
    <option value="Ortega (Tolima)">Ortega (Tolima)</option>
    <option value="Ospina (Nariño)">Ospina (Nariño)</option>
    <option value="Otanche (Boyacá)">Otanche (Boyacá)</option>
    <option value="Ovejas (Sucre)">Ovejas (Sucre)</option>
    <option value="Pachavita (Boyacá)">Pachavita (Boyacá)</option>
    <option value="Pacho (Cundinamarca)">Pacho (Cundinamarca)</option>
    <option value="Pacoa (Boyacá)">Pacoa (Boyacá)</option>
    <option value="Pácora (Caldas)">Pácora (Caldas)</option>
    <option value="Padilla (Cauca)">Padilla (Cauca)</option>
    <option value="Paez (Cauca)">Paez (Cauca)</option>
    <option value="Páez (Boyacá)">Páez (Boyacá)</option>
    <option value="Paicol (Huila)">Paicol (Huila)</option>
    <option value="Pailitas (Cesar)">Pailitas (Cesar)</option>
    <option value="Paime (Cundinamarca)">Paime (Cundinamarca)</option>
    <option value="Paipa (Boyacá)">Paipa (Boyacá)</option>
    <option value="Pajarito (Boyacá)">Pajarito (Boyacá)</option>
    <option value="Palermo (Huila)">Palermo (Huila)</option>
<option value="Palestina (Caldas)">Palestina (Caldas)</option>
<option value="Palestina (Huila)">Palestina (Huila)</option>
<option value="Palmar (Santander)">Palmar (Santander)</option>
<option value="Palmar de Varela (Atlántico)">Palmar de Varela (Atlántico)</option>
<option value="Palmas del Socorro (Santander)">Palmas del Socorro (Santander)</option>
<option value="Palmira (Valle del Cauca)">Palmira (Valle del Cauca)</option>
<option value="Palmito (Sucre)">Palmito (Sucre)</option>
<option value="Palocabildo (Tolima)">Palocabildo (Tolima)</option>
<option value="Pamplona (Norte de Santander)">Pamplona (Norte de Santander)</option>
<option value="Pamplonita (Norte de Santander)">Pamplonita (Norte de Santander)</option>
<option value="Pana Pana (Casanare)">Pana Pana (Casanare)</option>
<option value="Pandi (Cundinamarca)">Pandi (Cundinamarca)</option>
<option value="Panqueba (Boyacá)">Panqueba (Boyacá)</option>
<option value="Papunaua (Guainía)">Papunaua (Guainía)</option>
<option value="Páramo (Santander)">Páramo (Santander)</option>
<option value="Paratebueno (Cundinamarca)">Paratebueno (Cundinamarca)</option>
<option value="Pasca (Cundinamarca)">Pasca (Cundinamarca)</option>
<option value="Pasto (Nariño)">Pasto (Nariño)</option>
<option value="Patía (Cauca)">Patía (Cauca)</option>
<option value="Pauna (Boyacá)">Pauna (Boyacá)</option>
<option value="Paya (Boyacá)">Paya (Boyacá)</option>
<option value="Paz de Ariporo (Casanare)">Paz de Ariporo (Casanare)</option>
<option value="Paz de Río (Boyacá)">Paz de Río (Boyacá)</option>
<option value="Pedraza (Tolima)">Pedraza (Tolima)</option>
<option value="Pelaya (Cesar)">Pelaya (Cesar)</option>
<option value="Peñol (Antioquia)">Peñol (Antioquia)</option>
<option value="Pensilvania (Caldas)">Pensilvania (Caldas)</option>
<option value="Peque (Antioquia)">Peque (Antioquia)</option>
<option value="Pereira (Risaralda)">Pereira (Risaralda)</option>
<option value="Pesca (Boyacá)">Pesca (Boyacá)</option>
<option value="Piamonte (Cauca)">Piamonte (Cauca)</option>
<option value="Piedecuesta (Santander)">Piedecuesta (Santander)</option>
<option value="Piedras (Tolima)">Piedras (Tolima)</option>
<option value="Piendamó (Cauca)">Piendamó (Cauca)</option>
<option value="Pijao (Quindío)">Pijao (Quindío)</option>
<option value="Pijiño del Carmen (Magdalena)">Pijiño del Carmen (Magdalena)</option>
<option value="Pinchote (Santander)">Pinchote (Santander)</option>
<option value="Pinillos (Bolívar)">Pinillos (Bolívar)</option>
<option value="Piojó (Atlántico)">Piojó (Atlántico)</option>
<option value="Pisba (Boyacá)">Pisba (Boyacá)</option>
<option value="Pital (Boyacá)">Pital (Boyacá)</option>
<option value="Pitalito (Huila)">Pitalito (Huila)</option>
<option value="Pivijay (Magdalena)">Pivijay (Magdalena)</option>
<option value="Planadas (Tolima)">Planadas (Tolima)</option>
<option value="Planeta Rica (Córdoba)">Planeta Rica (Córdoba)</option>
<option value="Plato (Magdalena)">Plato (Magdalena)</option>
<option value="Policarpa (Nariño)">Policarpa (Nariño)</option>
<option value="Polonuevo (Atlántico)">Polonuevo (Atlántico)</option>
<option value="Ponedera (Atlántico)">Ponedera (Atlántico)</option>
<option value="Popayán (Cauca)">Popayán (Cauca)</option>
<option value="Pore (Casanare)">Pore (Casanare)</option>
<option value="Potosí (Nariño)">Potosí (Nariño)</option>
<option value="Pradera (Valle del Cauca)">Pradera (Valle del Cauca)</option>
<option value="Prado (Tolima)">Prado (Tolima)</option>
<option value="Providencia (Nariño)">Providencia (Nariño)</option>
<option value="Providencia (San Andrés y Providencia)">Providencia (San Andrés y Providencia)</option>
<option value="Pueblo Bello (Cesar)">Pueblo Bello (Cesar)</option>
<option value="Pueblo Nuevo (Córdoba)">Pueblo Nuevo (Córdoba)</option>
<option value="Pueblo Rico (Risaralda)">Pueblo Rico (Risaralda)</option>
<option value="Pueblorrico (Antioquia)">Pueblorrico (Antioquia)</option>
<option value="Puebloviejo (Magdalena)">Puebloviejo (Magdalena)</option>
<option value="Puente Nacional (Santander)">Puente Nacional (Santander)</option>
<option value="Puerres (Nariño)">Puerres (Nariño)</option>
<option value="Puerto Alegría (Amazonas)">Puerto Alegría (Amazonas)</option>
<option value="Puerto Arica (Amazonas)">Puerto Arica (Amazonas)</option>
<option value="Puerto Asís (Putumayo)">Puerto Asís (Putumayo)</option>
<option value="Puerto Berrío (Antioquia)">Puerto Berrío (Antioquia)</option>
<option value="Puerto Boyacá (Boyacá)">Puerto Boyacá (Boyacá)</option>
<option value="Puerto Caicedo (Putumayo)">Puerto Caicedo (Putumayo)</option>
<option value="Puerto Carreño (Vichada)">Puerto Carreño (Vichada)</option>
<option value="Puerto Colombia (Atlántico)">Puerto Colombia (Atlántico)</option>
<option value="Puerto Colombia (Cundinamarca)">Puerto Colombia (Cundinamarca)</option>
<option value="Puerto Concordia (Meta)">Puerto Concordia (Meta)</option>
<option value="Puerto Escondido (Córdoba)">Puerto Escondido (Córdoba)</option>
<option value="Puerto Gaitán (Meta)">Puerto Gaitán (Meta)</option>
<option value="Puerto Guzmán (Putumayo)">Puerto Guzmán (Putumayo)</option>
<option value="Puerto Libertador (Córdoba)">Puerto Libertador (Córdoba)</option>
<option value="Puerto Lleras (Meta)">Puerto Lleras (Meta)</option>
<option value="Puerto López (Meta)">Puerto López (Meta)</option>
<option value="Puerto Nare (Antioquia)">Puerto Nare (Antioquia)</option>
<option value="Puerto Nariño (Amazonas)">Puerto Nariño (Amazonas)</option>
<option value="Puerto Parra (Santander)">Puerto Parra (Santander)</option>
<option value="Puerto Rico (Caquetá)">Puerto Rico (Caquetá)</option>
<option value="Puerto Rico (Meta)">Puerto Rico (Meta)</option>
<option value="Puerto Rondón (Arauca)">Puerto Rondón (Arauca)</option>
<option value="Puerto Salgar (Cundinamarca)">Puerto Salgar (Cundinamarca)</option>
<option value="Puerto Santander (Norte de Santander)">Puerto Santander (Norte de Santander)</option>
<option value="Puerto Santander (Santander)">Puerto Santander (Santander)</option>
<option value="Puerto Tejada (Cauca)">Puerto Tejada (Cauca)</option>
<option value="Puerto Triunfo (Antioquia)">Puerto Triunfo (Antioquia)</option>
<option value="Puerto Wilches (Santander)">Puerto Wilches (Santander)</option>
<option value="Pulí (Cundinamarca)">Pulí (Cundinamarca)</option>
<option value="Pupiales (Nariño)">Pupiales (Nariño)</option>
<option value="Puracé (Cauca)">Puracé (Cauca)</option>
<option value="Purificación (Tolima)">Purificación (Tolima)</option>
<option value="Purísima (Córdoba)">Purísima (Córdoba)</option>
<option value="Quebradanegra (Caldas)">Quebradanegra (Caldas)</option>
<option value="Quetame (Cundinamarca)">Quetame (Cundinamarca)</option>
<option value="Quibdó (Chocó)">Quibdó (Chocó)</option>
<option value="Quimbaya (Quindío)">Quimbaya (Quindío)</option>
<option value="Quinchía (Risaralda)">Quinchía (Risaralda)</option>
<option value="Quípama (Boyacá)">Quípama (Boyacá)</option>
<option value="Quipile (Cundinamarca)">Quipile (Cundinamarca)</option>
<option value="Ragonvalia (Norte de Santander)">Ragonvalia (Norte de Santander)</option>
<option value="Ramiriquí (Boyacá)">Ramiriquí (Boyacá)</option>
<option value="Ráquira (Boyacá)">Ráquira (Boyacá)</option>
<option value="Recetor (Casanare)">Recetor (Casanare)</option>
<option value="Regidor (Norte de Santander)">Regidor (Norte de Santander)</option>
<option value="Remedios (Antioquia)">Remedios (Antioquia)</option>
<option value="Remolino (Magdalena)">Remolino (Magdalena)</option>
<option value="Repelón (Atlántico)">Repelón (Atlántico)</option>
<option value="Restrepo (Meta)">Restrepo (Meta)</option>
<option value="Restrepo (Valle del Cauca)">Restrepo (Valle del Cauca)</option>
<option value="Retiro (Antioquia)">Retiro (Antioquia)</option>
<option value="Ricaurte (Cundinamarca)">Ricaurte (Cundinamarca)</option>
<option value="Ricaurte (Nariño)">Ricaurte (Nariño)</option>
<option value="Río de Oro (Cesar)">Río de Oro (Cesar)</option>
<option value="Río Iro (Chocó)">Río Iro (Chocó)</option>
<option value="Río Quito (Chocó)">Río Quito (Chocó)</option>
<option value="Río Viejo (Bolívar)">Río Viejo (Bolívar)</option>
<option value="Rioblanco (Tolima)">Rioblanco (Tolima)</option>
<option value="Riofrío (Valle del Cauca)">Riofrío (Valle del Cauca)</option>
<option value="Riohacha (La Guajira)">Riohacha (La Guajira)</option>
<option value="Rionegro (Antioquia)">Rionegro (Antioquia)</option>
<option value="Rionegro (Santander)">Rionegro (Santander)</option>
<option value="Riosucio (Caldas)">Riosucio (Caldas)</option>
<option value="Riosucio (Chocó)">Riosucio (Chocó)</option>
<option value="Risaralda (Caldas)">Risaralda (Caldas)</option>
<option value="Rivera (Huila)">Rivera (Huila)</option>
<option value="Roberto Payán (Nariño)">Roberto Payán (Nariño)</option>
<option value="Roldanillo (Valle del Cauca)">Roldanillo (Valle del Cauca)</option>
<option value="Roncesvalles (Tolima)">Roncesvalles (Tolima)</option>
<option value="Rondón (Boyacá)">Rondón (Boyacá)</option>
<option value="Rosas (Cauca)">Rosas (Cauca)</option>
<option value="Rovira (Tolima)">Rovira (Tolima)</option>
<option value="Rozo (Cundinamarca)">Rozo (Cundinamarca)</option>
<option value="Rubiataba (Guainía)">Rubiataba (Guainía)</option>
<option value="sabaneta(antioquia)">sabatenta(antioquia)</option>
<option value="Sabana de Torres (Santander)">Sabana de Torres (Santander)</option>
<option value="Sabanagrande (Atlántico)">Sabanagrande (Atlántico)</option>
<option value="Sabanalarga (Atlántico)">Sabanalarga (Atlántico)</option>
<option value="Sabanalarga (Casanare)">Sabanalarga (Casanare)</option>
<option value="Sabanalarga (Norte de Santander)">Sabanalarga (Norte de Santander)</option>
<option value="Sabanas de San Ángel (Magdalena)">Sabanas de San Ángel (Magdalena)</option>
<option value="Saboyá (Boyacá)">Saboyá (Boyacá)</option>
<option value="Sácama (Casanare)">Sácama (Casanare)</option>
<option value="Sáchica (Boyacá)">Sáchica (Boyacá)</option>
<option value="Sahagún (Córdoba)">Sahagún (Córdoba)</option>
<option value="Saladoblanco (Huila)">Saladoblanco (Huila)</option>
<option value="Salamina (Caldas)">Salamina (Caldas)</option>
<option value="Salamina (Magdalena)">Salamina (Magdalena)</option>
<option value="Salazar de Las Palmas (Norte de Santander)">Salazar de Las Palmas (Norte de Santander)</option>
<option value="Saldaña (Tolima)">Saldaña (Tolima)</option>
<option value="Salento (Quindío)">Salento (Quindío)</option>
<option value="Salgar (Antioquia)">Salgar (Antioquia)</option>
<option value="San Agustín (Huila)">San Agustín (Huila)</option>
<option value="San Alberto (Cesar)">San Alberto (Cesar)</option>
<option value="San Andrés (San Andrés y Providencia)">San Andrés (San Andrés y Providencia)</option>
<option value="San Andrés de Cuerquía (Antioquia)">San Andrés de Cuerquía (Antioquia)</option>
<option value="San Andrés de Sotavento (Córdoba)">San Andrés de Sotavento (Córdoba)</option>
<option value="San Antero (Córdoba)">San Antero (Córdoba)</option>
<option value="San Antonio (Tolima)">San Antonio (Tolima)</option>
<option value="San Antonio del Tequendama (Cundinamarca)">San Antonio del Tequendama (Cundinamarca)</option>
<option value="San Benito (Santander)">San Benito (Santander)</option>
<option value="San Benito Abad (Sucre)">San Benito Abad (Sucre)</option>
<option value="San Bernardo (Nariño)">San Bernardo (Nariño)</option>
<option value="San Bernardo (Cundinamarca)">San Bernardo (Cundinamarca)</option>
<option value="San Bernardo del Viento (Córdoba)">San Bernardo del Viento (Córdoba)</option>
<option value="San Calixto (Norte de Santander)">San Calixto (Norte de Santander)</option>
<option value="San Carlos (Córdoba)">San Carlos (Córdoba)</option>
<option value="San Carlos (Antioquia)">San Carlos (Antioquia)</option>
<option value="San Carlos de Guaroa (Meta)">San Carlos de Guaroa (Meta)</option>
<option value="San Cayetano (Norte de Santander)">San Cayetano (Norte de Santander)</option>
<option value="San Cayetano (Cundinamarca)">San Cayetano (Cundinamarca)</option>
<option value="San Cristóbal (Bolívar)">San Cristóbal (Bolívar)</option>
<option value="San Diego (Cesar)">San Diego (Cesar)</option>
<option value="San Eduardo (Boyacá)">San Eduardo (Boyacá)</option>
<option value="San Estanislao (Bolívar)">San Estanislao (Bolívar)</option>
<option value="San Fernando (Bolívar)">San Fernando (Bolívar)</option>
<option value="San Francisco (Antioquia)">San Francisco (Antioquia)</option>
<option value="San Francisco (Putumayo)">San Francisco (Putumayo)</option>
<option value="San Gil (Santander)">San Gil (Santander)</option>
<option value="San Jacinto (Bolívar)">San Jacinto (Bolívar)</option>
<option value="San Jacinto del Cauca (Bolívar)">San Jacinto del Cauca (Bolívar)</option>
<option value="San Jerónimo (Antioquia)">San Jerónimo (Antioquia)</option>
<option value="San Joaquín (Santander)">San Joaquín (Santander)</option>
<option value="San José (Caldas)">San José (Caldas)</option>
<option value="San José (Nariño)">San José (Nariño)</option>
<option value="San José de Miranda (Santander)">San José de Miranda (Santander)</option>
<option value="San José de Montaña (Antioquia)">San José de Montaña (Antioquia)</option>
<option value="San José de Pare (Boyacá)">San José de Pare (Boyacá)</option>
<option value="San José del Fragua (Caquetá)">San José del Fragua (Caquetá)</option>
<option value="San José del Guaviare (Guaviare)">San José del Guaviare (Guaviare)</option>
<option value="San José del Palmar (Chocó)">San José del Palmar (Chocó)</option>
<option value="San Juan de Arama (Meta)">San Juan de Arama (Meta)</option>
<option value="San Juan de Betulia (Sucre)">San Juan de Betulia (Sucre)</option>
<option value="San Juan de Dios (Nariño)">San Juan de Dios (Nariño)</option>
<option value="San Juan de Río Seco (Cundinamarca)">San Juan de Río Seco (Cundinamarca)</option>
<option value="San Juan de Urabá (Antioquia)">San Juan de Urabá (Antioquia)</option>
<option value="San Juan del Cesar (La Guajira)">San Juan del Cesar (La Guajira)</option>
<option value="San Juan Nepomuceno (Bolívar)">San Juan Nepomuceno (Bolívar)</option>
<option value="San Juanito (Meta)">San Juanito (Meta)</option>
<option value="San Lorenzo (Nariño)">San Lorenzo (Nariño)</option>
<option value="San Luis (Antioquia)">San Luis (Antioquia)</option>
<option value="San Luis (Tolima)">San Luis (Tolima)</option>
<option value="San Luis de Gaceno (Boyacá)">San Luis de Gaceno (Boyacá)</option>
<option value="San Luis de Palenque (Casanare)">San Luis de Palenque (Casanare)</option>
<option value="San Marcos (Sucre)">San Marcos (Sucre)</option>
<option value="San Martín (Cesar)">San Martín (Cesar)</option>
<option value="San Martín (Meta)">San Martín (Meta)</option>
<option value="San Martín (Cundinamarca)">San Martín (Cundinamarca)</option>
<option value="San Mateo (Boyacá)">San Mateo (Boyacá)</option>
<option value="San Miguel (Putumayo)">San Miguel (Putumayo)</option>
<option value="San Miguel (Santander)">San Miguel (Santander)</option>
<option value="San Miguel de Sema (Boyacá)">San Miguel de Sema (Boyacá)</option>
<option value="San Onofre (Sucre)">San Onofre (Sucre)</option>
<option value="San Pablo (Nariño)">San Pablo (Nariño)</option>
<option value="San Pablo (Bolívar)">San Pablo (Bolívar)</option>
<option value="San Pablo de Borbur (Boyacá)">San Pablo de Borbur (Boyacá)</option>
<option value="San Pedro (Sucre)">San Pedro (Sucre)</option>
<option value="San Pedro (Valle del Cauca)">San Pedro (Valle del Cauca)</option>
<option value="San Pedro de Cartago (Nariño)">San Pedro de Cartago (Nariño)</option>
<option value="San Pedro de Urabá (Antioquia)">San Pedro de Urabá (Antioquia)</option>
<option value="San Pelayo (Córdoba)">San Pelayo (Córdoba)</option>
<option value="San Rafael (Antioquia)">San Rafael (Antioquia)</option>
<option value="San Roque (Antioquia)">San Roque (Antioquia)</option>
<option value="San Sebastián (Magdalena)">San Sebastián (Magdalena)</option>
<option value="San Sebastián de Buenavista (Magdalena)">San Sebastián de Buenavista (Magdalena)</option>
<option value="San Vicente (Antioquia)">San Vicente (Antioquia)</option>
<option value="San Vicente de Chucurí (Santander)">San Vicente de Chucurí (Santander)</option>
<option value="San Vicente del Caguán (Caquetá)">San Vicente del Caguán (Caquetá)</option>
<option value="San Zenón (Magdalena)">San Zenón (Magdalena)</option>
<option value="Sandona (Nariño)">Sandona (Nariño)</option>
<option value="Santa Ana (Magdalena)">Santa Ana (Magdalena)</option>
<option value="Santa Bárbara (Santander)">Santa Bárbara (Santander)</option>
<option value="Santa Bárbara (Antioquia)">Santa Bárbara (Antioquia)</option>
<option value="Santa Bárbara (Nariño)">Santa Bárbara (Nariño)</option>
<option value="Santa Bárbara (Bolívar)">Santa Bárbara (Bolívar)</option>
<option value="Santa Catalina (Bolívar)">Santa Catalina (Bolívar)</option>
<option value="Santa Fé (Antioquia)">Santa Fé (Antioquia)</option>
<option value="Santa Lucía (Atlántico)">Santa Lucía (Atlántico)</option>
<option value="Santa María (Boyacá)">Santa María (Boyacá)</option>
<option value="Santa María (Huila)">Santa María (Huila)</option>
<option value="Santa Marta (Magdalena)">Santa Marta (Magdalena)</option>
<option value="Santa Rosa (Bolívar)">Santa Rosa (Bolívar)</option>
<option value="Santa Rosa (Cauca)">Santa Rosa (Cauca)</option>
<option value="Santa Rosa de Cabal (Risaralda)">Santa Rosa de Cabal (Risaralda)</option>
<option value="Santa Rosa de Osos (Antioquia)">Santa Rosa de Osos (Antioquia)</option>
<option value="Santa Rosa del Sur (Bolívar)">Santa Rosa del Sur (Bolívar)</option>
<option value="Santa Rosalía (Vichada)">Santa Rosalía (Vichada)</option>
<option value="Santa Sofía (Boyacá)">Santa Sofía (Boyacá)</option>
<option value="Santa Teresa (Santander)">Santa Teresa (Santander)</option>
<option value="Santa Teresa (Boyacá)">Santa Teresa (Boyacá)</option>
<option value="Santa Victoria (Boyacá)">Santa Victoria (Boyacá)</option>
<option value="Santacruz (Nariño)">Santacruz (Nariño)</option>
<option value="Santafé de Antioquia (Antioquia)">Santafé de Antioquia (Antioquia)</option>
<option value="Santana (Boyacá)">Santana (Boyacá)</option>
<option value="Santander de Quilichao (Cauca)">Santander de Quilichao (Cauca)</option>
<option value="Santiago (Norte de Santander)">Santiago (Norte de Santander)</option>
<option value="Santiago (Putumayo)">Santiago (Putumayo)</option>
<option value="Santiago de Tolú (Sucre)">Santiago de Tolú (Sucre)</option>
<option value="Santo Domingo (Antioquia)">Santo Domingo (Antioquia)</option>
<option value="Santo Tomás (Atlántico)">Santo Tomás (Atlántico)</option>
<option value="Santuario (Antioquia)">Santuario (Antioquia)</option>
<option value="Sapuyes (Nariño)">Sapuyes (Nariño)</option>
<option value="Saravena (Arauca)">Saravena (Arauca)</option>
<option value="Sardinata (Norte de Santander)">Sardinata (Norte de Santander)</option>
<option value="Sasaima (Cundinamarca)">Sasaima (Cundinamarca)</option>
<option value="Sativanorte (Boyacá)">Sativanorte (Boyacá)</option>
<option value="Sativasur (Boyacá)">Sativasur (Boyacá)</option>
<option value="Segovia (Antioquia)">Segovia (Antioquia)</option>
<option value="Sesquilé (Cundinamarca)">Sesquilé (Cundinamarca)</option>
<option value="Sevilla (Valle del Cauca)">Sevilla (Valle del Cauca)</option>
<option value="Siachoque (Boyacá)">Siachoque (Boyacá)</option>
<option value="Sibaté (Cundinamarca)">Sibaté (Cundinamarca)</option>
<option value="Sibundoy (Putumayo)">Sibundoy (Putumayo)</option>
<option value="Silos (Norte de Santander)">Silos (Norte de Santander)</option>
<option value="Silvania (Cundinamarca)">Silvania (Cundinamarca)</option>
<option value="Silvia (Cauca)">Silvia (Cauca)</option>
<option value="Simacota (Santander)">Simacota (Santander)</option>
<option value="Simijaca (Cundinamarca)">Simijaca (Cundinamarca)</option>
<option value="Simití (Bolívar)">Simití (Bolívar)</option>
<option value="Sincelejo (Sucre)">Sincelejo (Sucre)</option>
<option value="Sincé (Sucre)">Sincé (Sucre)</option>
<option value="Sipí (Chocó)">Sipí (Chocó)</option>
<option value="Sitionuevo (Magdalena)">Sitionuevo (Magdalena)</option>
<option value="Soacha (Cundinamarca)">Soacha (Cundinamarca)</option>
<option value="Soatá (Boyacá)">Soatá (Boyacá)</option>
<option value="Socha (Boyacá)">Socha (Boyacá)</option>
<option value="Socorro (Santander)">Socorro (Santander)</option>
<option value="Socotá (Boyacá)">Socotá (Boyacá)</option>
<option value="Sogamoso (Boyacá)">Sogamoso (Boyacá)</option>
<option value="Solano (Caquetá)">Solano (Caquetá)</option>
<option value="Soledad (Atlántico)">Soledad (Atlántico)</option>
<option value="Solita (Caquetá)">Solita (Caquetá)</option>
<option value="Somondoco (Boyacá)">Somondoco (Boyacá)</option>
<option value="Sonson (Antioquia)">Sonson (Antioquia)</option>
<option value="Sopetrán (Antioquia)">Sopetrán (Antioquia)</option>
<option value="Soplaviento (Bolívar)">Soplaviento (Bolívar)</option>
<option value="Sopó (Cundinamarca)">Sopó (Cundinamarca)</option>
<option value="Sora (Boyacá)">Sora (Boyacá)</option>
<option value="Soracá (Boyacá)">Soracá (Boyacá)</option>
<option value="Sotaquirá (Boyacá)">Sotaquirá (Boyacá)</option>
<option value="Sotara (Cauca)">Sotara (Cauca)</option>
<option value="Sotomayor (Nariño)">Sotomayor (Nariño)</option>
<option value="Suaita (Santander)">Suaita (Santander)</option>
<option value="Suan (Atlántico)">Suan (Atlántico)</option>
<option value="Suárez (Cauca)">Suárez (Cauca)</option>
<option value="Suárez (Tolima)">Suárez (Tolima)</option>
<option value="Suaza (Huila)">Suaza (Huila)</option>
<option value="Subachoque (Cundinamarca)">Subachoque (Cundinamarca)</option>
<option value="Subía (Cundinamarca)">Subía (Cundinamarca)</option>
<option value="Sucre (Sucre)">Sucre (Sucre)</option>
<option value="Sucre (Cauca)">Sucre (Cauca)</option>
<option value="Suesca (Cundinamarca)">Suesca (Cundinamarca)</option>
<option value="Supatá (Cundinamarca)">Supatá (Cundinamarca)</option>
<option value="Supía (Caldas)">Supía (Caldas)</option>
<option value="Suratá (Santander)">Suratá (Santander)</option>
<option value="Susa (Cundinamarca)">Susa (Cundinamarca)</option>
<option value="Susacón (Boyacá)">Susacón (Boyacá)</option>
<option value="Sutamarchán (Boyacá)">Sutamarchán (Boyacá)</option>
<option value="Sutatausa (Cundinamarca)">Sutatausa (Cundinamarca)</option>
<option value="Sutatenza (Boyacá)">Sutatenza (Boyacá)</option>
<option value="Tabio (Cundinamarca)">Tabio (Cundinamarca)</option>
<option value="Tadó (Chocó)">Tadó (Chocó)</option>
<option value="Talaigua Nuevo (Bolívar)">Talaigua Nuevo (Bolívar)</option>
<option value="Tamalameque (Cesar)">Tamalameque (Cesar)</option>
<option value="Támara (Casanare)">Támara (Casanare)</option>
<option value="Támara (Norte de Santander)">Támara (Norte de Santander)</option>
<option value="Tamesis (Antioquia)">Tamesis (Antioquia)</option>
<option value="Taminango (Nariño)">Taminango (Nariño)</option>
<option value="Tangua (Nariño)">Tangua (Nariño)</option>
<option value="Taraira (Vaupés)">Taraira (Vaupés)</option>
<option value="Tarapacá (Amazonas)">Tarapacá (Amazonas)</option>
<option value="Tarazá (Antioquia)">Tarazá (Antioquia)</option>
<option value="Tarqui (Huila)">Tarqui (Huila)</option>
<option value="Tarso (Antioquia)">Tarso (Antioquia)</option>
<option value="Tasco (Boyacá)">Tasco (Boyacá)</option>
<option value="Tauramena (Casanare)">Tauramena (Casanare)</option>
<option value="Tausa (Cundinamarca)">Tausa (Cundinamarca)</option>
<option value="Tello (Huila)">Tello (Huila)</option>
<option value="Tena (Cundinamarca)">Tena (Cundinamarca)</option>
<option value="Tenerife (Magdalena)">Tenerife (Magdalena)</option>
<option value="Tenjo (Cundinamarca)">Tenjo (Cundinamarca)</option>
<option value="Tenza (Boyacá)">Tenza (Boyacá)</option>
<option value="Teorama (Norte de Santander)">Teorama (Norte de Santander)</option>
<option value="Teruel (Huila)">Teruel (Huila)</option>
<option value="Tesalia (Huila)">Tesalia (Huila)</option>
<option value="Tibacuy (Cundinamarca)">Tibacuy (Cundinamarca)</option>
<option value="Tibaná (Boyacá)">Tibaná (Boyacá)</option>
<option value="Tibasosa (Boyacá)">Tibasosa (Boyacá)</option>
<option value="Tibirita (Cundinamarca)">Tibirita (Cundinamarca)</option>
<option value="Tibú (Norte de Santander)">Tibú (Norte de Santander)</option>
<option value="Tierralta (Córdoba)">Tierralta (Córdoba)</option>
<option value="Timaná (Huila)">Timaná (Huila)</option>
<option value="Timbío (Cauca)">Timbío (Cauca)</option>
<option value="Timbiquí (Cauca)">Timbiquí (Cauca)</option>
<option value="Tinjacá (Boyacá)">Tinjacá (Boyacá)</option>
<option value="Tipacoque (Boyacá)">Tipacoque (Boyacá)</option>
<option value="Tiquisio (Bolívar)">Tiquisio (Bolívar)</option>
<option value="Titiribí (Antioquia)">Titiribí (Antioquia)</option>
<option value="Toca (Boyacá)">Toca (Boyacá)</option>
<option value="Tocaima (Cundinamarca)">Tocaima (Cundinamarca)</option>
<option value="Tocancipá (Cundinamarca)">Tocancipá (Cundinamarca)</option>
<option value="Togüí (Boyacá)">Togüí (Boyacá)</option>
<option value="Toledo (Antioquia)">Toledo (Antioquia)</option>
<option value="Toledo (Norte de Santander)">Toledo (Norte de Santander)</option>
<option value="Tolú Viejo (Sucre)">Tolú Viejo (Sucre)</option>
<option value="Tona (Santander)">Tona (Santander)</option>
<option value="Tópaga (Boyacá)">Tópaga (Boyacá)</option>
<option value="Topaipí (Cundinamarca)">Topaipí (Cundinamarca)</option>
<option value="Toribio (Cauca)">Toribio (Cauca)</option>
<option value="Toro (Valle del Cauca)">Toro (Valle del Cauca)</option>
<option value="Tota (Boyacá)">Tota (Boyacá)</option>
<option value="Totoró (Cauca)">Totoró (Cauca)</option>
<option value="Trinidad (Casanare)">Trinidad (Casanare)</option>
<option value="Trujillo (Valle del Cauca)">Trujillo (Valle del Cauca)</option>
<option value="Tubará (Atlántico)">Tubará (Atlántico)</option>
<option value="Tuluá (Valle del Cauca)">Tuluá (Valle del Cauca)</option>
<option value="Tumaco (Nariño)">Tumaco (Nariño)</option>
<option value="Tunja (Boyacá)">Tunja (Boyacá)</option>
<option value="Tununguá (Boyacá)">Tununguá (Boyacá)</option>
<option value="Túquerres (Nariño)">Túquerres (Nariño)</option>
<option value="Turbaco (Bolívar)">Turbaco (Bolívar)</option>
<option value="Turbaná (Bolívar)">Turbaná (Bolívar)</option>
<option value="Turbo (Antioquia)">Turbo (Antioquia)</option>
<option value="Turmequé (Boyacá)">Turmequé (Boyacá)</option>
<option value="Tuta (Boyacá)">Tuta (Boyacá)</option>
<option value="Tutazá (Boyacá)">Tutazá (Boyacá)</option>
<option value="Ubalá (Cundinamarca)">Ubalá (Cundinamarca)</option>
<option value="Ubaque (Cundinamarca)">Ubaque (Cundinamarca)</option>
<option value="Ulloa (Valle del Cauca)">Ulloa (Valle del Cauca)</option>
<option value="Umbita (Boyacá)">Umbita (Boyacá)</option>
<option value="Une (Cundinamarca)">Une (Cundinamarca)</option>
<option value="Unguía (Chocó)">Unguía (Chocó)</option>
<option value="Unión Panamericana (Chocó)">Unión Panamericana (Chocó)</option>
<option value="Uramita (Antioquia)">Uramita (Antioquia)</option>
<option value="Uribe (Meta)">Uribe (Meta)</option>
<option value="Uribia (La Guajira)">Uribia (La Guajira)</option>
<option value="Urrao (Antioquia)">Urrao (Antioquia)</option>
<option value="Urumita (La Guajira)">Urumita (La Guajira)</option>
<option value="Usiacurí (Atlántico)">Usiacurí (Atlántico)</option>
<option value="Útica (Cundinamarca)">Útica (Cundinamarca)</option>
<option value="Valdivia (Antioquia)">Valdivia (Antioquia)</option>
<option value="Valencia (Córdoba)">Valencia (Córdoba)</option>
<option value="Valle de San José (Santander)">Valle de San José (Santander)</option>
<option value="Valle de San Juan (Tolima)">Valle de San Juan (Tolima)</option>
<option value="Valle del Guamuez (Putumayo)">Valle del Guamuez (Putumayo)</option>
<option value="Valledupar (Cesar)">Valledupar (Cesar)</option>
<option value="Valparaíso (Antioquia)">Valparaíso (Antioquia)</option>
<option value="Valparaíso (Caquetá)">Valparaíso (Caquetá)</option>
<option value="Vegachí (Antioquia)">Vegachí (Antioquia)</option>
<option value="Vélez (Santander)">Vélez (Santander)</option>
<option value="Venadillo (Tolima)">Venadillo (Tolima)</option>
<option value="Venecia (Antioquia)">Venecia (Antioquia)</option>
<option value="Venecia (Cundinamarca)">Venecia (Cundinamarca)</option>
<option value="Ventaquemada (Boyacá)">Ventaquemada (Boyacá)</option>
<option value="Vergara (Cundinamarca)">Vergara (Cundinamarca)</option>
<option value="Versalles (Valle del Cauca)">Versalles (Valle del Cauca)</option>
<option value="Vetas (Santander)">Vetas (Santander)</option>
<option value="Vianí (Cundinamarca)">Vianí (Cundinamarca)</option>
<option value="Victoria (Caldas)">Victoria (Caldas)</option>
<option value="Vigía del Fuerte (Antioquia)">Vigía del Fuerte (Antioquia)</option>
<option value="Vijes (Valle del Cauca)">Vijes (Valle del Cauca)</option>
<option value="Villa Caro (Norte de Santander)">Villa Caro (Norte de Santander)</option>
<option value="Villa de Leyva (Boyacá)">Villa de Leyva (Boyacá)</option>
<option value="Villa de San Diego de Ubate (Cundinamarca)">Villa de San Diego de Ubate (Cundinamarca)</option>
<option value="Villa del Rosario (Norte de Santander)">Villa del Rosario (Norte de Santander)</option>
<option value="Villa Rica (Cauca)">Villa Rica (Cauca)</option>
<option value="Villagarzón (Putumayo)">Villagarzón (Putumayo)</option>
<option value="Villagómez (Nariño)">Villagómez (Nariño)</option>
<option value="Villahermosa (Tolima)">Villahermosa (Tolima)</option>
<option value="Villamaría (Caldas)">Villamaría (Caldas)</option>
<option value="Villanueva (Bolívar)">Villanueva (Bolívar)</option>
<option value="Villanueva (Casanare)">Villanueva (Casanare)</option>
<option value="Villanueva (La Guajira)">Villanueva (La Guajira)</option>
<option value="Villanueva (Santander)">Villanueva (Santander)</option>
<option value="Villapinzón (Cundinamarca)">Villapinzón (Cundinamarca)</option>
<option value="Villarrica (Tolima)">Villarrica (Tolima)</option>
<option value="Villavicencio (Meta)">Villavicencio (Meta)</option>
<option value="Villavieja (Huila)">Villavieja (Huila)</option>
<option value="Villeta (Cundinamarca)">Villeta (Cundinamarca)</option>
<option value="Viotá (Cundinamarca)">Viotá (Cundinamarca)</option>
<option value="Viracachá (Boyacá)">Viracachá (Boyacá)</option>
<option value="Vistahermosa (Meta)">Vistahermosa (Meta)</option>
<option value="Viterbo (Caldas)">Viterbo (Caldas)</option>
<option value="Yacopí (Cundinamarca)">Yacopí (Cundinamarca)</option>
<option value="Yacuanquer (Nariño)">Yacuanquer (Nariño)</option>
<option value="Yaguará (Huila)">Yaguará (Huila)</option>
<option value="Yalí (Antioquia)">Yalí (Antioquia)</option>
<option value="Yarumal (Antioquia)">Yarumal (Antioquia)</option>
<option value="Yavaraté (Vaupés)">Yavaraté (Vaupés)</option>
<option value="Yolombó (Antioquia)">Yolombó (Antioquia)</option>
<option value="Yondó (Antioquia)">Yondó (Antioquia)</option>
<option value="Yopal (Casanare)">Yopal (Casanare)</option>
<option value="Yotoco (Valle del Cauca)">Yotoco (Valle del Cauca)</option>
<option value="Yumbo (Valle del Cauca)">Yumbo (Valle del Cauca)</option>
<option value="Zambrano (Bolívar)">Zambrano (Bolívar)</option>
<option value="Zapatoca (Santander)">Zapatoca (Santander)</option>
<option value="Zapayán (Magdalena)">Zapayán (Magdalena)</option>
<option value="Zaragoza (Antioquia)">Zaragoza (Antioquia)</option>
<option value="Zarzal (Valle del Cauca)">Zarzal (Valle del Cauca)</option>
<option value="Zetaquira (Boyacá)">Zetaquira (Boyacá)</option>
<option value="Zipacón (Cundinamarca)">Zipacón (Cundinamarca)</option>
<option value="Zipaquirá (Cundinamarca)">Zipaquirá (Cundinamarca)</option>
<option value="Zona Bananera (Magdalena)">Zona Bananera (Magdalena)</option>

    </>
  );
};

export default Ciudades;
